/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:5ad5261b-52ca-468b-ac92-f0746a8ce435",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_jdwS2a7cp",
    "aws_user_pools_web_client_id": "4mo1um7djdrs6hpeboaakpk87j",
    "oauth": {
        "domain": "talkn-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://cover.talkn.io/,https://localhost:8000/",
        "redirectSignOut": "https://localhost:8000/,https://localhost:8000/,https://cover.localhost/,https://cover.localhost/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
